import type { NextPage } from "next";
import Head from "next/head";
import { GetServerSideProps } from "next";
import { prisma } from "../db/client";

const Home: NextPage<{ poll: string }> = ({ poll }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{poll}</h1>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const poll = await prisma.poll.findMany();
  return { props: { poll: JSON.stringify(poll) } };
};
